### ISSUE TITLE
No package 'gdk-3.0' found

### ISSUE THREAD

**Issue by jhessin** [gtk-rs/gtk-rs.github.io#120]
I am trying to compile a basic hello world and I keep running into the following error:

```
Compiling gdk-sys v0.9.0
error: failed to run custom build command for `gdk-sys v0.9.0`

Caused by:
  process didn't exit successfully: `/home/jhessin/Documents/bitbucket/rust-rev/target/debug/build/gdk-sys-15a474474e7b5275/build-script-build` (exit code: 1)
--- stderr
`"pkg-config" "--libs" "--cflags" "gdk-3.0 >= 3.22"` did not exit successfully: exit code: 1
--- stderr
Package gdk-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gdk-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gdk-3.0' found
```

I have checked and my $PKG_CONFIG_PATH variable is: /usr/lib/x86_64-linux-gnu/pkgconfig/
and gdk-3.0.pc IS in this directory. I was a bit confused about all the "Features" listed [here](https://gtk-rs.org/docs-src/tutorial/version), but I tried quite a few of them with no success. Here is my Cargo.toml as it stands now:

```toml
[package]
name = "rust-rev"
version = "0.1.0"
authors = ["Jim Hessin <jhessin@gmail.com>"]
edition = "2018"


# orbtk = { git = "https://gitlab.redox-os.org/redox-os/orbtk.git" }
[dependencies.gtk]
version = "0.7.0"
default-features = false
features = [ "v3_22" ]

[dependencies.gio]
version = "0.7.0"
features = [ "v2_44" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#
# [dependencies.rusqlite]
# version = "0.18.0"
# features = ["bundled"]
```
